# Generated by Django 4.0.4 on 2022-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worksname', models.CharField(max_length=100)),
                ('Timelimit', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestData',
        ),
    ]
